/* This file is generated by venus-protocol.  See vn_protocol_renderer.h. */

/*
 * Copyright 2020 Google LLC
 * SPDX-License-Identifier: MIT
 */

#ifndef VN_PROTOCOL_RENDERER_SURFACE_H
#define VN_PROTOCOL_RENDERER_SURFACE_H

#include "vn_protocol_renderer_structs.h"

#pragma GCC diagnostic push
#if !defined(__clang__) && defined(__GNUC__) && __GNUC__ >= 12
#pragma GCC diagnostic ignored "-Wdangling-pointer"
#endif
#pragma GCC diagnostic ignored "-Wpointer-arith"
#pragma GCC diagnostic ignored "-Wunused-parameter"

/* struct VkSurfaceCreateInfoWEBROGUE chain */

static inline void *
vn_decode_VkSurfaceCreateInfoWEBROGUE_pnext_temp(struct vn_cs_decoder *dec)
{
    /* no known/supported struct */
    if (vn_decode_simple_pointer(dec))
        vn_cs_decoder_set_fatal(dec);
    return NULL;
}

static inline void
vn_decode_VkSurfaceCreateInfoWEBROGUE_self_temp(struct vn_cs_decoder *dec, VkSurfaceCreateInfoWEBROGUE *val)
{
    /* skip val->{sType,pNext} */
    vn_decode_VkFlags(dec, &val->flags);
    vn_decode_uint32_t(dec, &val->webrogue_window_id);
}

static inline void
vn_decode_VkSurfaceCreateInfoWEBROGUE_temp(struct vn_cs_decoder *dec, VkSurfaceCreateInfoWEBROGUE *val)
{
    VkStructureType stype;
    vn_decode_VkStructureType(dec, &stype);
    if (stype != VK_STRUCTURE_TYPE_SURFACE_CREATE_INFO_WEBROGUE)
        vn_cs_decoder_set_fatal(dec);

    val->sType = stype;
    val->pNext = vn_decode_VkSurfaceCreateInfoWEBROGUE_pnext_temp(dec);
    vn_decode_VkSurfaceCreateInfoWEBROGUE_self_temp(dec, val);
}

static inline void
vn_replace_VkSurfaceCreateInfoWEBROGUE_handle_self(VkSurfaceCreateInfoWEBROGUE *val)
{
    /* skip val->sType */
    /* skip val->pNext */
    /* skip val->flags */
    /* skip val->webrogue_window_id */
}

static inline void
vn_replace_VkSurfaceCreateInfoWEBROGUE_handle(VkSurfaceCreateInfoWEBROGUE *val)
{
    struct VkBaseOutStructure *pnext = (struct VkBaseOutStructure *)val;

    do {
        switch ((int32_t)pnext->sType) {
        case VK_STRUCTURE_TYPE_SURFACE_CREATE_INFO_WEBROGUE:
            vn_replace_VkSurfaceCreateInfoWEBROGUE_handle_self((VkSurfaceCreateInfoWEBROGUE *)pnext);
            break;
        default:
            /* ignore unknown/unsupported struct */
            break;
        }
        pnext = pnext->pNext;
    } while (pnext);
}

static inline void vn_decode_vkDestroySurfaceKHR_args_temp(struct vn_cs_decoder *dec, struct vn_command_vkDestroySurfaceKHR *args)
{
    vn_decode_VkInstance_lookup(dec, &args->instance);
    vn_decode_VkSurfaceKHR_lookup(dec, &args->surface);
    if (vn_decode_simple_pointer(dec)) {
        vn_cs_decoder_set_fatal(dec);
    } else {
        args->pAllocator = NULL;
    }
}

static inline void vn_replace_vkDestroySurfaceKHR_args_handle(struct vn_command_vkDestroySurfaceKHR *args)
{
    vn_replace_VkInstance_handle(&args->instance);
    vn_replace_VkSurfaceKHR_handle(&args->surface);
    /* skip args->pAllocator */
}

static inline void vn_encode_vkDestroySurfaceKHR_reply(struct vn_cs_encoder *enc, const struct vn_command_vkDestroySurfaceKHR *args)
{
    vn_encode_VkCommandTypeEXT(enc, &(VkCommandTypeEXT){VK_COMMAND_TYPE_vkDestroySurfaceKHR_EXT});

    /* skip args->instance */
    /* skip args->surface */
    /* skip args->pAllocator */
}

static inline void vn_decode_vkCreateSurfaceWEBROGUE_args_temp(struct vn_cs_decoder *dec, struct vn_command_vkCreateSurfaceWEBROGUE *args)
{
    vn_decode_VkInstance_lookup(dec, &args->instance);
    if (vn_decode_simple_pointer(dec)) {
        args->pCreateInfo = vn_cs_decoder_alloc_temp(dec, sizeof(*args->pCreateInfo));
        if (!args->pCreateInfo) return;
        vn_decode_VkSurfaceCreateInfoWEBROGUE_temp(dec, (VkSurfaceCreateInfoWEBROGUE *)args->pCreateInfo);
    } else {
        args->pCreateInfo = NULL;
        vn_cs_decoder_set_fatal(dec);
    }
    if (vn_decode_simple_pointer(dec)) {
        vn_cs_decoder_set_fatal(dec);
    } else {
        args->pAllocator = NULL;
    }
    if (vn_decode_simple_pointer(dec)) {
        args->pSurface = vn_cs_decoder_alloc_temp(dec, sizeof(*args->pSurface));
        if (!args->pSurface) return;
        vn_decode_VkSurfaceKHR(dec, args->pSurface);
    } else {
        args->pSurface = NULL;
        vn_cs_decoder_set_fatal(dec);
    }
}

static inline void vn_replace_vkCreateSurfaceWEBROGUE_args_handle(struct vn_command_vkCreateSurfaceWEBROGUE *args)
{
    vn_replace_VkInstance_handle(&args->instance);
    if (args->pCreateInfo)
        vn_replace_VkSurfaceCreateInfoWEBROGUE_handle((VkSurfaceCreateInfoWEBROGUE *)args->pCreateInfo);
    /* skip args->pAllocator */
    /* skip args->pSurface */
}

static inline void vn_encode_vkCreateSurfaceWEBROGUE_reply(struct vn_cs_encoder *enc, const struct vn_command_vkCreateSurfaceWEBROGUE *args)
{
    vn_encode_VkCommandTypeEXT(enc, &(VkCommandTypeEXT){VK_COMMAND_TYPE_vkCreateSurfaceWEBROGUE_EXT});

    vn_encode_VkResult(enc, &args->ret);
    /* skip args->instance */
    /* skip args->pCreateInfo */
    /* skip args->pAllocator */
    if (vn_encode_simple_pointer(enc, args->pSurface))
        vn_encode_VkSurfaceKHR(enc, args->pSurface);
}

static inline void vn_dispatch_vkDestroySurfaceKHR(struct vn_dispatch_context *ctx, VkCommandFlagsEXT flags)
{
    struct vn_command_vkDestroySurfaceKHR args;

    if (!ctx->dispatch_vkDestroySurfaceKHR) {
        vn_cs_decoder_set_fatal(ctx->decoder);
        return;
    }

    vn_decode_vkDestroySurfaceKHR_args_temp(ctx->decoder, &args);
    if (!args.instance) {
        vn_cs_decoder_set_fatal(ctx->decoder);
        return;
    }

    if (!vn_cs_decoder_get_fatal(ctx->decoder))
        ctx->dispatch_vkDestroySurfaceKHR(ctx, &args);

    if ((flags & VK_COMMAND_GENERATE_REPLY_BIT_EXT) && !vn_cs_decoder_get_fatal(ctx->decoder)) {
        if (vn_cs_encoder_acquire(ctx->encoder)) {
            vn_encode_vkDestroySurfaceKHR_reply(ctx->encoder, &args);
            vn_cs_encoder_release(ctx->encoder);
        }
    }

    vn_cs_decoder_reset_temp_pool(ctx->decoder);
}

static inline void vn_dispatch_vkCreateSurfaceWEBROGUE(struct vn_dispatch_context *ctx, VkCommandFlagsEXT flags)
{
    struct vn_command_vkCreateSurfaceWEBROGUE args;

    if (!ctx->dispatch_vkCreateSurfaceWEBROGUE) {
        vn_cs_decoder_set_fatal(ctx->decoder);
        return;
    }

    vn_decode_vkCreateSurfaceWEBROGUE_args_temp(ctx->decoder, &args);
    if (!args.instance) {
        vn_cs_decoder_set_fatal(ctx->decoder);
        return;
    }

    if (!vn_cs_decoder_get_fatal(ctx->decoder))
        ctx->dispatch_vkCreateSurfaceWEBROGUE(ctx, &args);

#ifdef DEBUG
    if (!vn_cs_decoder_get_fatal(ctx->decoder) && vn_dispatch_should_log_result(args.ret))
        vn_dispatch_debug_log(ctx, "vkCreateSurfaceWEBROGUE returned %d", args.ret);
#endif

    if ((flags & VK_COMMAND_GENERATE_REPLY_BIT_EXT) && !vn_cs_decoder_get_fatal(ctx->decoder)) {
        if (vn_cs_encoder_acquire(ctx->encoder)) {
            vn_encode_vkCreateSurfaceWEBROGUE_reply(ctx->encoder, &args);
            vn_cs_encoder_release(ctx->encoder);
        }
    }

    vn_cs_decoder_reset_temp_pool(ctx->decoder);
}

#pragma GCC diagnostic pop

#endif /* VN_PROTOCOL_RENDERER_SURFACE_H */
